version: '2'
services:
    jhipstersampleapplication-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterSampleApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterSampleApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
